### ISSUE TITLE
邀约

### ISSUE THREAD

**Issue by amxuejin** [airyland/Jsource#2]
李政，有兴趣接触一下，前端与物联网结合后的样子吗？

有一个基于物联网的移动支付项目AllPayCloud，机智云内部创业性质。

机智云：http://www.gizwits.com

AllPayCloud：http://www.allpaycloud.cn

**Comment by airyland** [comment]
Sorry, I don't consider another job at the moment, and email may be a properer way.

**Comment by amxuejin** [comment]
Sorry to disturb you.
